site:
  author: iamkyu
  description: Hello To-Do Application

toggle:
  auth: true
  onlineUsersCounter: false

logging:
  level:
    todoapp: DEBUG
    org.springframework:
      boot: INFO
      web: DEBUG